-- 기존 MEMBER 테이블이 있다면 삭제
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS MEMBERS;

-- MEMBERS 테이블 생성 (Member 엔티티와 일치)
CREATE TABLE MEMBERS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL DEFAULT 'USER'
);

