name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - admin-service
          - board-service
          - eureka-server
          - frontend-service
          - gateway-service
          - inventory-service
          - member-service
          - order-service
          - product-service

    steps:
      - uses: actions/checkout@v3

      - name: Docker 빌드 - ${{ matrix.service }}
        run: docker build -f ${{ matrix.service }}/Dockerfile -t tori-coffee/${{ matrix.service }} .